<style>
	.modal-dialog {
    width: 67%;
}

.activestatus{
		color:green;
		background:green;
		border-radius:30px; width:15px; height:15px;
		cursor:pointer
		
	}
	
	.de-activestatus{
		color:green;
		background:red;
		border-radius:30px; width:15px; height:15px;
		cursor:pointer;
		
		
	}



</style>


<div class="row">
          <div class="col-xs-12"> 
            <!-- PAGE CONTENT BEGINS -->
            <div class="alert alert-block alert-success">
              <button type="button" class="close" data-dismiss="alert"> <i class="ace-icon fa fa-times"></i> </button>
              <i class="ace-icon fa fa-check green"></i>Add State Master</strong>, </div>
            <div class="row">
              <div class="space-6"></div>
              <div class="vspace-12-sm"></div>
            </div>
            <div class="row">
              <div class="col-xs-12">
                <h3  >Add States Master</h3>
                <div class="filter">
                 <div class="panel-body" style="padding:0 !important">
                  <div class="col-lg-6">View Records>></div>
                  </div>
                </div>
                <div class="portlet-body">
                  <?php 

                  $form=$this->form; 
                $form->prepare();


        $form->setAttribute('action',$this->url('zfcadmin/admin',
                  array("controller"=>"state","action"=>"performsearch")));
        $form->setAttribute('method','post');
        $form->setAttribute('autocomplete','off');
        $form->setAttribute('id','bookingFilter');
        
        $form->setAttribute('onSubmit','return performsearch(this.id,"'.$this->url("zfcadmin/admin",
                  array("controller"=>"state","action"=>"performsearch")).'",performsearchresults)');

        echo $this->form()->openTag($form);

                  ?>
                   
                    <div id="myTabContent" class="tab-content">
                      <div class="tab-pane fade active in" id="home">
                        <div class="col-sm-col-sm-offset-1" style="margin: 10px auto 0px !important;padding: 0 10px;">
                          <div class="row">
                                                <div class="form-group clearfix margintopbottom20">
                          						 <label id="point_airport" class="col-sm-2 control-label labelalign ">Country Name
                          						 </label>
                                                   <div class="col-sm-3">
                                                    <?php 

                                                     echo $this->formElement($form->get('country_id'));

                                                    ?>
                                                    
                                                    </div>

                         						  <label id="flight_nos" class="col-sm-2 control-label labelalign ">State Name</label>
                                                  <div class="col-sm-2 ">
                                                     <input id="search_countryName" class=" form-control inputchange" placeholder="State Name" type="text" 
                                                     onkeyup="countrysearchactions($(this).val(),'<?= $this->serverUrl().$this->url().'/state/countrysearch'?>',countrysearchresp,$('#bookingFilter :input[name=country_id]').val())" name="state_name">
                                                     <div class="col-sm-3" id="countrysearchresults" style="position: absolute;overflow-y:scroll;background:#FFF;width:93%;height:auto;z-index: 9999;display:none;">
                                                     </div>                                    
                                                  </div>
                                                 
                            				<div class="col-sm-1">
                                                     <input class="btn btn-red defaultbtnsearch searchBooking"  type="submit" name="submit" value="Search">
                                                    </div>
                                                    
                                                    <div class="col-sm-1">
                                                     <input  id="showaddform"  class="btn btn-red defaultbtnsearch searchBooking"  type="submit" name="submit" value="Add">
                                                    </div>
                                                 </div>
                                             </div>
                          
                                             </div>

                          
                           
                        </div>
                      </div>
                   <?php   
echo $this->form()->closeTag();

        ?>                                   
          
                    </div>
                
                 
                  <div class="filter">
                   <div class="panel-body" style="padding:0 !important; cursor:pointer;">
                  <div class="col-lg-6" >Add Update Records>>
                    </div>
                     <!--<div class="col-lg-6" id="showaddform" align="right" style="font-size:18px;">+
                    </div>-->
                  </div>
   
                </div>
                
                
              
               
                
          <div id="addForm" class="tab-content dontshow">
                   <?php 

                $form=$this->form; 
                $form->prepare();


        $form->setAttribute('action',$this->url('zfcadmin/admin',array('controller'=>'State','action'=>'add')));
        $form->setAttribute('method','post');
        $form->setAttribute('autocomplete','off');
        $form->setAttribute('id','StateForm');
        $action = $this->serverUrl().$this->url().'/state/add';
        $form->setAttribute('onSubmit',"return SubmitFormAction($(this).attr('id'),'".$action."',addformResp)");

        echo $this->form()->openTag($form);
// echo $this->formCollection($form);
                ?>
        
            
            
            <div class="tab-pane fade active in" id="driver_tab">
              <div class="col-sm-col-sm-offset-1" style="margin: 10px auto 0px !important;padding: 0 10px;">
                
                <div class="row">
                                                <div class="form-group clearfix margintopbottom20">
                           <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate($form->get('country_id')->getLabel()) ?>
                           </label>
                                                  <div class="col-sm-2">
                                                     <?php 
                                                     echo $this->formHidden($form->get('id'));
                                                     echo $this->formElement($form->get('country_id'));
                                                     ?> 
                                                     <span class="showerror"></span>                                      
                                                  </div>
                                                 
                           <label id="flight_nos" class="col-sm-1 control-label labelalign ">
                            <?= $this->translate($form->get('state_name')->getLabel()) ?>
                           </label>
                                                  <div class="col-sm-2 dontshow" id="passCname" Cname="">
                                                     <?php 
                                                     echo $this->formHidden($form->get('master_state_id'));

                                                     echo $this->formElement($form->get('state_name'));
                                                     ?>
                                                     <span class="showerror"></span> <div class="col-sm-3 searchboxresults" id="searchresults" style="position: absolute;
  overflow-y:scroll;
  background:#FFF;
  width:93%;
  height:auto;
  z-index: 9999;display:none;">
                                                     </div>                                       
                                                  </div>
                                                  
                                                   <label id="flight_nos" class="col-sm-1 control-label labelalign ">
                            <?= $this->translate($form->get('IsActive')->getLabel()) ?>
                           </label>
                                                  <div class="col-sm-2">
                                                     <?php 
                                                     echo $this->formElement($form->get('IsActive'));
                                                     ?> 
                                                     <span class="showerror"></span>                                      
                                                  </div>
                                                  
                                                  <div class="col-sm-1 ">
                                                     <?php 
                                                     echo $this->formRow($form->get('submit'));
                                                     ?>                                    
                                                  </div>
                                                  
                                                  
                                                 </div>
                                             </div>
                                             
                                             
              </div>
            </div>
          
        <?php   
echo $this->form()->closeTag();

        ?>                                   
                                                  </div>
                                           
                                              
              <div id="editForm" class="tab-content dontshow">
          </div>
                   
                  
                <div class="col-lg-12" style="background-color:#FFF;" id="radiosearch" fld="tbl_country">
                  
                  <div class="col-lg-1"><div class="radio">
                                                <label>
                                                    <input type="radio" value="1" id="optionsRadios1" name="optionsRadios" onchange="RadioSearch($(this).val(),'tbl_state','<?= $this->serverUrl().$this->url().'/state/ajaxradiosearch';?>',radioSearchResult)" ><strong>Active</strong>
                                                </label>
                                                <br>
 
                                            </div>
                  
                  
                  
                  
                  </div>
                  
                  
                   <div class="col-lg-1">
                    <div class="radio">
                                                <label>
                                                    <input type="radio" value="0" id="optionsRadios1" name="optionsRadios" onchange="RadioSearch($(this).val(),'tbl_state','<?= $this->serverUrl().$this->url().'/state/ajaxradiosearch';?>',radioSearchResult)"><strong>In-Active</strong>
                                                </label>
                                                
                                              
                    </div>
                  </div>
                  
                    
                   
                    <div class="delete pull-right">
                      <button class="btn btn-red defaultbtnsearch searchBooking" onclick="statuschangeall('<?= $this->serverUrl().$this->url().'/state/statuschangeall';?>',statuschangeallresp,0)">De-Activate Selected</button>                                    
                    </div>
                    
                    <div class="col-lg-2 pull-right">
                    <div class="delete">
                      <button class="btn btn-red defaultbtnsearch searchBooking" onclick="statuschangeall('<?= $this->serverUrl().$this->url().'/state/statuschangeall';?>',statuschangeallresp,1)">Activate Selected</button>                                    
                    </div>
                  </div>
                  
                 <div class="col-lg-2 pull-right">
                    <div class="delete">
                      <button class="btn btn-red defaultbtnsearch searchBooking" onclick="delselected('<?= $this->serverUrl().$this->url().'/state/delmultiple';?>',delmultipleresp)">Delete Selected</button>                                              
                    </div>
                  </div>

                  </div>
                  
                  <div class="col-sm-12">

                 
                   
</div>         <div class="col-md-12">
                    <div class="table-responsive">
                      <table id="dynamic-table" class="table table-striped table-bordered table-hover">
                    <thead>
                      <tr>
                         
                           <th><input type="checkbox" value="" id="checkAll" onclick="checkall(this.id)" > </th>
                         <th> Sr. No. </th>
                        <th>State Name</th>
                        <th>Country Name</th>
                        <th class="hidden-480">Modified Date</th>
                        <th class="hidden-480">Created Date</th>
                        <th class="hidden-480">Status</th>
                        <th class="hidden-480">Modified By</th>
                        <th><b>Actions</b></th>
                      </tr>
                    </thead>
                    <tbody>
                      <?php 
                      $i=1;
                      foreach ($states as $state) {
                      
                      ?>
                      <tr>
                            <td><input type="checkbox" value="<?=$state->id?>" class="checkme" name="checkme[]"> </td>  
                        <td> <?=$i?></td>
                        <td><?= $state->state_name?></td>                       
                        <td class="hidden-480"><?= $state->country_name?></td>
                        <td class="hidden-480"><?= date('l d-m-y',strtotime($state->created_date))?></td>
                        <td class="hidden-480"><?= date('l d-m-y',strtotime($state->modified_date))?></td>
                        <td class="hidden-480" align="center">
						
						<?php $status = ($state->IsActive==1)? 'Active': 'In-Active';
                        $statuscolor = ($state->IsActive==1)? 'activestatus': 'de-activestatus';
                         ?>
                          <div name="ChangeStatus" id="changestatus<?=$i;?>" onclick="changestatusquick(<?=$state->id?>,<?= ($state->IsActive==0)?0:1; ?>,'<?= $this->serverUrl().$this->url().'/state/changestatus';?>',changstatusresult);" class="<?=$statuscolor?>">
                        </div>
						
						<!--<?php $status = ($state->IsActive==1)? 'Active': 'In-Active';
                        $statuscolor = ($state->IsActive==1)? 'lightgreen': 'red';
                         ?>
                          <button name="ChangeStatus" id="changestatus<?=$i;?>" onclick="changestatusquick(<?=$state->id?>,<?= ($state->IsActive==0)?0:1; ?>,'<?= $this->serverUrl().$this->url().'/state/changestatus';?>',changstatusresult);"  style="background:<?=$statuscolor?>;color:white;font-weight:bold;"><?= $status?>
                        </button>--></td>
                        <td class="hidden-480"><?php echo ($state->modified_by==1)? 'Admin': 'NotByAdmin'; ?></td>
                        <td>
                        <div class="hidden-sm hidden-xs action-buttons"> 
                        <!--<a class="blue" href="<?php echo $this->url('zfcadmin/admin',array('controller'=>'state','action'=>'view','id'=>$state->id)); ?>"> 
                        <i class="ace-icon fa fa-search-plus bigger-130"></i> </a>-->
                        
                         <a class="blue" style="cursor:pointer;" data-toggle="modal" data-target="#myModal" tar="indview<?=$i?>"> <i class="ace-icon fa fa-search-plus bigger-130"></i> </a>
                        
                         <a class="green" href="javascript:void(0);" 
                          onclick="editbox(<?=$state->id?>,'<?= $this->serverUrl().$this->url('zfcadmin/admin',array('controller'=>'state','action'=>'edit','id'=>$state->id));
                        ?>',editformresp);"> <i class="ace-icon fa fa-pencil bigger-130"></i> </a> 

                         <a class="red" href="<?php echo $this->url('zfcadmin/admin',array('controller'=>'state','action'=>'delete','id'=>$state->id)); ?>" onclick="return confirm('are you sure you want to delete');"> <i class="ace-icon fa fa-trash-o bigger-130"></i> </a> </div>
                          </td>
                      </tr>
                      
                       
                      
                      <?php 
                      $i++;
                    }
                      ?>
                    </tbody>
                  </table>
                      
                      
                      
                      
                    </div>
                 </div>
              </div>
              
              
              
              
              
              <div class="col-sm-12"> 
              </div>
            </div>
            <!-- /.col --> 
<div id="myModal" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Modal Header</h4>
      </div>
      <div class="modal-body">
          <tr class="dontshow" id="indview<?=$i?>" aria-expanded="true">
                     
                	<td colspan="8">
                    <div aria-expanded="true" class="panel-body accordion-body packageDetails1 collapse in" id="accordion1">
               
                          <div class="tab-content" id="myTabContent">
        
              <div class="col-sm-col-sm-offset-1" style="margin: 10px auto 0px !important;padding: 0 10px;">
                <div class="row">
                   <div class="form-group clearfix margintopbottom20 col-sm-12">
                           <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate('State Name'); ?>
                           </label>
                                                  <div class="col-sm-3">
                                                     <?php 
                                                     
                                                     echo $state->state_name;
                                                     ?>                                    
                                                  </div>
                           <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate('Country Name'); ?>
                           </label>
                                                  <div class="col-sm-3">
                                                     <?php 
                                                     echo $state->country_name;
                                                     ?>                                    
                                                  </div>
                                                 </div>
                                             </div>
                                             <div class="row">
                                                <div class="form-group clearfix margintopbottom20 col-sm-12">
                        <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate('Modified By'); ?>
                           </label>
                                                  <div class="col-sm-3">
                                                     <?php 
                                                     echo ($state->modified_by==1)?'Admin':'Not Available Now';
                                                     ?>                                    
                                                  </div>
                                                 
                            <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate('Status'); ?>
                           </label>
                                                  <div class="col-sm-3">
                                                     <?php 
                                                     echo ($state->IsActive==1)? 'Active':'In-Active';
                                                     ?>                                    
                                                  </div>
                                                 </div>
                                             </div>

                                          <div class="row">
                                                <div class="form-group clearfix margintopbottom20 col-sm-12">
                          <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate('Created Date'); ?>
                           </label>
                                                  <div class="col-sm-3">
                                                     <?php 
                                                     echo date('l d-m-Y',strtotime($state->created_date));
                                                     ?>                                    
                                                  </div>
                                                 
                            <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate('Modified Date'); ?>
                           </label>
                                                  <div class="col-sm-3">
                                                     <?php 
                                                     echo date('l d-m-Y',strtotime($state->modified_date));
                                                     ?>                                    
                                                  </div>
                                                 </div>
                                             </div>  
                                             
              </div>
           
          </div>
      </div>
                    
                                             
                       </td>
                    </tr>      
      </div>
      <div class="modal-footer">
        <button type="button"data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>
            
            <!-- /.row -->
            
            <div class="hr hr-18 dotted hr-double"></div>
            <div class="row">
              <div class="col-xs-12">
                
                <div> 
         
      </div>
      <!-- /.page-content --> 
    </div>
  </div>
  <!-- /.main-content -->
  
     
  <a href="#" id="btn-scroll-up" class="btn-scroll-up btn btn-sm btn-inverse"> <i class="ace-icon fa fa-angle-double-up icon-only bigger-110"></i> </a> </div>
<!-- /.main-container --> 

<!-- basic scripts --> 

<!--[if !IE]> -->