<style>
	.modal-dialog {
    width: 67%;
}

.activestatus{
		color:green;
		background:green;
		border-radius:30px; width:15px; height:15px;
		cursor:pointer
		
	}
	
	.de-activestatus{
		color:green;
		background:red;
		border-radius:30px; width:15px; height:15px;
		cursor:pointer;
		
		
	}



</style>




<div class="row">
          <div class="col-xs-12"> 
            <!--<div class="row">
              <div class="space-6"></div>
              <div class="vspace-12-sm"></div>
            </div>-->
            
            
            <div class="row">
              <div class="col-xs-12">
                <h3  >Country Master</h3>
                <div class="filter">
                  <div class="panel-body" style="padding:0 !important">
                  <div class="col-lg-6">View Records>></div>
                  </div>
                </div>
                <div class="portlet-body">
                  <form id="bookingFilter" method="post" autocomplete="off" action="<?=$this->url('zfcadmin/admin',
                  array("controller"=>"country","action"=>"performsearch"))?>" onsubmit="return performsearch(this.id,'<?=$this->url('zfcadmin/admin',
                  array("controller"=>"country","action"=>"performsearch"))?>',performsearchresults)">
                    <div id="myTabContent" class="tab-content">
                      <div class="tab-pane fade active in" id="home">
                        <div class="col-sm-col-sm-offset-1" style="margin: 10px auto 0px !important;padding: 0 10px;">
                          <div class="row">
                                                <div class="form-group clearfix margintopbottom20">
                           <label id="flight_nos" class="col-sm-2 control-label labelalign ">Country Name</label>
                                                  <div class="col-sm-2 ">
                                                     <input id="search_countryName" class=" form-control inputchange" placeholder="India" type="text" 
                                                     onkeyup="countrysearchactions($(this).val(),'<?= $this->serverUrl().$this->url().'/country/countrysearch'?>',countrysearchresp,'country_name')" name="country_name">
                                                     <div class="col-sm-3" id="countrysearchresults" style="position: absolute;overflow-y:scroll;background:#FFF;width:93%;height:auto;z-index: 9999;display:none;">
                                                     </div>                                    
                                                  </div>
                                                 
                            <label id="point_airport" class="col-sm-2 control-label labelalign ">Country Code
</label>
                                                   <div class="col-sm-1">
                                                    <input id="search_countryCode" class=" form-control inputchange" placeholder="Country Code" type="text"name="country_code">
                                                    </div>
                                                    
                                                    <label id="flight_nos" class="col-sm-1 control-label labelalign ">Dial Code</label>
                                                  <div class="col-sm-1 ">
                                                     <input id="search_dialCode" class=" form-control inputchange" placeholder="Country Code" type="number"
                                                    name="dial_code">
                                                     </div>  
                                                      
                                                  <div class="col-sm-1 ">
                                                     <input class="btn btn-red defaultbtnsearch searchBooking"  type="submit" name="submit" value="Search">
                                                     </div>
                                                     <div class="col-sm-2 ">
                                                     <input class="btn btn-red defaultbtnsearch" id="showaddform" type="submit" name="submit" value="Add">
                                                     </div>
                                                    
                                                    
                                                 </div>
                                             </div>
                          <div class="row">
                                                <!--<div class="form-group clearfix margintopbottom20">
                           <label id="flight_nos" class="col-sm-2 control-label labelalign ">Dial Code</label>
                                                  <div class="col-sm-3 ">
                                                     <input id="search_dialCode" class=" form-control inputchange" placeholder="Country Code" type="number"
                                                    name="dial_code">
                                                     </div>  
                                                      <label id="flight_nos" class="col-sm-2 control-label labelalign "></label>
                                                  <div class="col-sm-1 ">
                                                     <input class="btn btn-red defaultbtnsearch searchBooking"  type="submit" name="submit" value="Search">
                                                     </div>
                                                     <div class="col-sm-2 ">
                                                     <input class="btn btn-red defaultbtnsearch" id="showaddform" style="background:#333 !important;"  type="submit" name="submit" value="Add Country">
                                                     </div>
                                                                                       
                                                  </div>-->
                                                 
                             
                                                   <div class="col-sm-3">
                                                    
                                                    </div>
                                                 </div>
                                             </div>

                          
                           
                        </div>
                      </div>
                    </form>
                    </div>
                  
   
                
                
                 
                  <div class="filter">
                  <div class="panel-body" style="padding:0 !important; cursor:pointer;">
                  <div class="col-lg-6" >Add Update Records>>
                    </div>
                     <!--<div class="col-lg-6" id="showaddform" align="right">+
                    </div>-->
                  </div>
                     
                </div>
                <div id="addForm" class="tab-content dontshow">
            <?php 

                $form=$this->form; 
                $form->prepare();


        $form->setAttribute('action',$this->url('zfcadmin/admin',array('controller'=>'Country','action'=>'add')));
        $form->setAttribute('method','post');
        $form->setAttribute('autocomplete','off');
        $form->setAttribute('id','CountryForm');
        $action = $this->serverUrl().$this->url().'/country/add';
        $form->setAttribute('onSubmit',"return SubmitFormAction($(this).attr('id'),'".$action."',addformResp)");

        echo $this->form()->openTag($form);
// echo $this->formCollection($form);
                ?>
            
            <div class="tab-pane fade active in" id="driver_tab">
              <div class="container col-sm-col-sm-offset-1" style="margin: 10px auto 0px !important;padding: 0 10px;">
                
                <div class="row" style="position:relative;z-index:1;">
                                                <div class="form-group clearfix margintopbottom20">
                                                
                         						  <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate($form->get('country_name')->getLabel()) ?>
                           </label>
                                                  <div class="col-sm-2" id="addparent" >
                                                     <?php 
                                                     echo $this->formHidden($form->get('id'));
                                                     echo $this->formElement($form->get('country_name'));
                                                     ?> 
                                                     <span class="showerror"></span>   
                                                     <div class="col-sm-3 searchboxresults" id="searchresults" style="position: absolute;
  overflow-y:scroll;
  background:#FFF;
  width:93%;
  height:auto;
  z-index: 9999;display:none;">
                                                     </div>                                
                                                  </div>
                                                  

												  <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate($form->get('country_code')->getLabel()) ?>
                           </label>
                           
                                                  <div class="col-sm-1">
                                                     <?php 
                                                      
                                                     echo $this->formElement($form->get('country_code'));
                                                     ?>  
                                                     <span class="showerror"></span>                                   

                                                  </div>
                                                  
                                                 
                        						    <label id="flight_nos" class="col-sm-1 control-label labelalign ">
                            <?= $this->translate($form->get('dial_code')->getLabel()) ?>
                           </label>
                           
                         	                        <div class="col-sm-1" >
                                                     <?php 
                                                     echo $this->formHidden($form->get('master_country_id'));
                                                     echo $this->formElement($form->get('dial_code'));
                                                     ?>  
                                                     <span class="showerror"></span>                                   

                                                  </div>
                                                  
                                                  <div class="col-sm-1 pull-left">
                                                     <?php 
                                                     echo $this->formRow($form->get('submit'));
                                                     ?>                                    
                                                  </div>
                                                   <div class="col-sm-1 pull-left">
                                                       <a class="btn btn-red defaultbtnsearch searchBooking" href="javascript:void(0);" onclick="location.reload();">Cancel</a>                              
                                                  </div>
                                                  
                                                 </div>
                                             </div>
                                             <!--<div class="row">
                                                <div class="form-group clearfix margintopbottom20">
                         						 
                                                 
                            <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate($form->get('IsActive')->getLabel()) ?>
                           </label>
                                                  <div class="col-sm-3">
                                                     <?php 
                                                     echo $this->formElement($form->get('IsActive'));
                                                     ?> 
                                                     <span class="showerror"></span>                                   
                                                                                        
                                                  </div>
                                                 </div>
                                             </div>-->
                                             
              </div>
            </div>
            <?php   
echo $this->form()->closeTag();

        ?>
          </div>
          <div id="editForm" class="tab-content dontshow">
          </div>
                    <div class="clearfix"></div>
                  
                <div class="col-lg-12" style="background-color:#FFF;" id="radiosearch" fld="tbl_country">
                  
                  <div class="col-lg-1"><div class="radio">
                                                <label>
                                                    <input type="radio" value="1" id="optionsRadios1" name="optionsRadios" onchange="RadioSearch($(this).val(),'tbl_country','<?= $this->serverUrl().$this->url().'/country/ajaxradiosearch';?>',radioSearchResult)" ><strong>Active</strong>
                                                </label>
                                                <br>
 
                                            </div>
                  
                  
                  
                  
                  </div>
                  
                  
                   <div class="col-lg-1">
                    <div class="radio">
                                                <label>
                                                    <input type="radio" value="0" id="optionsRadios1" name="optionsRadios" onchange="RadioSearch($(this).val(),'tbl_country','<?= $this->serverUrl().$this->url().'/country/ajaxradiosearch';?>',radioSearchResult)"><strong>In-Active</strong>
                                                </label>
                                                
                                              
                    </div>
                  </div>
                  
                  
                   
                   
                  <div class="col-lg-2 pull-right">
                    <div class="delete">
                      <button class="btn btn-red defaultbtnsearch searchBooking" onclick="statuschangeall('<?= $this->serverUrl().$this->url().'/country/statuschangeall';?>',statuschangeallresp,0)">De-Activate Selected</button>                                    
                    </div>
                  </div>
                  
                  <div class="col-lg-2 pull-right">
                    <div class="delete">
                      <button class="btn btn-red defaultbtnsearch searchBooking" onclick="statuschangeall('<?= $this->serverUrl().$this->url().'/country/statuschangeall';?>',statuschangeallresp,1)">Activate Selected</button>                                    
                    </div>
                  </div>
                  <div class="col-lg-2 pull-right">
                    <div class="delete">
                      <button class="btn btn-red defaultbtnsearch searchBooking" onclick="delselected('<?= $this->serverUrl().$this->url().'/country/delmultiple';?>',delmultipleresp)">Delete Selected</button>                                              
                    </div>
                  </div>

                  </div>
                  
                  <div class="col-sm-12">

                   
</div>
                  
                  
                <div class="col-md-12">
                
                    <div class="table-responsive">
                      <table id="dynamic-table" class="table table-striped table-bordered table-hover">
                    <thead>
                      <tr>
                         
                         <th><input type="checkbox" value="" id="checkAll" onclick="checkall(this.id)" ></th>
                        <th>Sr. No. </th>
                        <th>Country Name</th>
                        <th>Dial Code</th>
                        <th class="hidden-480">Country Code</th>                       
                        <th class="hidden-480">Modified Date</th>
                        <th class="hidden-480">Created Date</th>
                        <th class="hidden-480">Status</th>
                        <th class="hidden-480">Modified By</th>
                        <th><b>Actions</b></th>
                      </tr>
                    </thead>
                    <tbody>
                      <?php 
                      $i=1;
                      foreach ($countries as $country) {
                      
                      ?>
                      
                      <tr>
                        <td><input type="checkbox" value="<?=$country->id?>" class="checkme" name="checkme[]"></td> 
                       <td><?=$i?></td>
                        <td ><?= $country->country_name?></td>
                                             
                        <td class="hidden-480"><?= $country->dial_code?></td>
                        <td><?= $country->country_code?></td>
                        <td class="hidden-480"><?= $country->created_date?></td>
                        <td class="hidden-480"><?= $country->modified_date?></td>
                        <td class="hidden-480" align="center">
						
						<?php $status = ($country->IsActive==1)? 'Active': 'In-Active';
                        $statuscolor = ($country->IsActive==1)? 'activestatus': 'de-activestatus';
                         ?>
                          <div name="ChangeStatus" id="changestatus<?=$i;?>" onclick="changestatusquick(<?=$country->id?>,<?= ($country->IsActive==0)?0:1; ?>,'<?= $this->serverUrl().$this->url().'/country/changestatus';?>',changstatusresult);" class="<?=$statuscolor?>">
                        </div>
						
						</td>
                        <td class="hidden-480"><?php echo ($country->modified_by==1)? 'Admin': 'NotByAdmin'; ?></td>
                        <td aria-expanded="false" class="accordion1"><div class="hidden-sm hidden-xs action-buttons"> <a class="blue" style="cursor:pointer;" data-toggle="modal" data-target="#myModal"  tar="indview<?=$i?>"> <i class="ace-icon fa fa-search-plus bigger-130"></i> </a> <a class="green" href="javascript:void(0);" onclick="editbox(<?=$country->id?>,'<?= $this->serverUrl().$this->url('zfcadmin/admin',array('controller'=>'country','action'=>'edit','id'=>$country->id));
                        ?>',editformresp);" > <i class="ace-icon fa fa-pencil bigger-130"></i> </a> <a class="red" href="<?php echo $this->url('zfcadmin/admin',array('controller'=>'country','action'=>'delete','id'=>$country->id)); ?>" onclick="return confirm('are you sure you want to delete');"> <i class="ace-icon fa fa-trash-o bigger-130"></i> </a> </div>
                          </td>
                      </tr>
                      
                      <!-- <?php echo $this->url('zfcadmin/admin',array('controller'=>'country','action'=>'edit','id'=>$country->id)); ?> -->
                      
                     
                      
                      
                      
                      
                      
                      <?php 
                      $i++;
                    }
                      ?>
                    </tbody>
                  </table>
                      
                      
                      
                      
                    </div>
                 </div>
              </div>
              
              
              
              
              
              <div class="col-sm-12"> 
                
                <!-- /.widget-box -->
                <!--<div  style="margin-top:20px;"> <a href="#" class="btn btn-red defaultbtnsearch searchBooking"><i class="fa fa-search" id="search_me" style="color:#fff; margin:5px"></i>Refresh</a> </div>-->
              </div>
            </div>
            <!-- /.col --> 

       
       
     
  <a href="#" id="btn-scroll-up" class="btn-scroll-up btn btn-sm btn-inverse"> <i class="ace-icon fa fa-angle-double-up icon-only bigger-110"></i> </a> 

</div></div>

<div id="myModal" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Modal Header</h4>
      </div>
      <div class="modal-body">
      
      
          <tr class="dontshow" id="indview<?=$i?>" aria-expanded="true">
                     
                	<td colspan="7">
                    <div aria-expanded="true" class="panel-body accordion-body packageDetails1 collapse in" id="accordion1">
               
                          <div class="tab-content" id="myTabContent">
        
              <div class="col-sm-col-sm-offset-1" style="margin: 10px auto 0px !important;padding: 0 10px;">
                <div class="row">
                   <div class="form-group clearfix margintopbottom20 col-sm-12">
                           <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate('Religion Name'); ?>
                           </label>
                                                  <div class="col-sm-3">
                                                     <?php 
                                                     
                                                     echo $Info->religion_name;
                                                     ?>                                    
                                                  </div>
                                                  <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate('Created Date'); ?>
                           </label>
                                                  <div class="col-sm-3">
                                                     <?php 
                                                     echo date('l d-m-Y',strtotime($Info->created_date));
                                                     ?>                                    
                                                  </div>
                           
                                                 </div>
                                             </div>
                                             <div class="row">
                                                <div class="form-group clearfix margintopbottom20 col-sm-12">
                        <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate('Modified By'); ?>
                           </label>
                                                  <div class="col-sm-3">
                                                     <?php 
                                                     echo ($Info->modified_by==1)?'Admin':'Not Available Now';
                                                     ?>                                    
                                                  </div>
                                                 
                            <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate('Status'); ?>
                           </label>
                                                  <div class="col-sm-3">
                                                     <?php 
                                                     echo ($Info->IsActive==1)? 'Active':'In-Active';
                                                     ?>                                    
                                                  </div>
                                                 </div>
                                             </div>

                                          <div class="row">
                                                <div class="form-group clearfix margintopbottom20 col-sm-12">
                          
                                                 
                            <label id="flight_nos" class="col-sm-2 control-label labelalign ">
                            <?= $this->translate('Modified Date'); ?>
                           </label>
                                                  <div class="col-sm-3">
                                                     <?php 
                                                     echo date('l d-m-Y',strtotime($Info->modified_date));
                                                     ?>                                    
                                                  </div>
                                                 </div>
                                             </div>  
                                             
              </div>
           
          </div>
      </div>
                    
                                             
                       </td>
                    </tr>   
      </div>
      <div class="modal-footer">
        <button type="button"data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

<!-- /.main-container --> 

<!-- basic scripts --> 

<!--[if !IE]> -->


